### PR TITLE
Restructure assets

### PR DESCRIPTION
**Pull request by beegee-tokyo**
@mtuxpe @carlrakwireless 
I restructured the repo to have all images in one place instead of a res/assets/images folder spread all over.
Please check all MD files that the images are loaded and that they are correct. 
There are same small differences in some MD files, if you have doubts, we can discuss here.

### CODE REVIEW

**Comment by mtuxpe** [comment]
First comment : It is better to use "Plug & Play" instead of "Plug&Play"

**Comment by beegee-tokyo** [comment]
Dear reviewers,
@mtuxpe @carlrakwireless 
Please use the review tools and approve the commits.
image

**Review by carlrakwireless — APPROVED** [review]
All good to me.

**Comment by mtuxpe** [comment]
Approved

**Pull request merged**
