### PR TITLE
Add tutorial files using Light Sensor and OLED

### PR DESCRIPTION
**Pull request by rallyuminga**
-This code use RAK1903 Ambient Light Sensor and RAK1921 OLED Display using RAK4631.

### CODE REVIEW

**Comment by rallyuminga** [comment]
Add tutorial files using Light Sensor and OLED

**Comment by beegee-tokyo** [comment]
@rallyuminga 
Can you check why it does not compile on RAK11200? 
If the code is not compatible with RAK11200, please add an empty file named **`.rak11200.test.skip`** in the same folder as the **`RAK4631_Light_Sensor_OLED_Screen.ino`** file. Then the automatic test build will skip the file for RAK11200 and only test for RAK4631 and RAK11300.

Thank you.

**Comment by rallyuminga** [comment]
> @rallyuminga Can you check why it does not compile on RAK11200? If the code is not compatible with RAK11200, please add an empty file named **`.rak11200.test.skip`** in the same folder as the **`RAK4631_Light_Sensor_OLED_Screen.ino`** file. Then the automatic test build will skip the file for RAK11200 and only test for RAK4631 and RAK11300.
> 
> Thank you.

@beegee-tokyo
I tested on the WisCore RAK11200 Board for the result compilation and enabled the verbose output of the Arduino IDE. It compiled successfully but has some warnings. See attached files for verification. Thank you!
RAK11200_OLED_Screen1
RAK11200_OLED_Screen2

**Comment by carlrakwireless** [comment]
@rallyuminga  do not have RAK11200 WisBlock Core.

I tested his code and works fine.

image

**Comment by beegee-tokyo** [comment]
My bad, the automatic test is not failing because of your pull-request. It fails because of something in the Adafruit libraries, and it fails only for RAK11200.
image

6 days ago there was no problem. No I get suddenly errors for these Adafruit library on RAK11200.

**Comment by carlrakwireless** [comment]
Hi @beegee-tokyo ,

Do we need anything else to merge this on WisBlock repo?

The marketing suddenly made Rally's article live 😅 

https://news.rakwireless.com/work-in-a-well-lighted-environment-measure-the-lux-with-wisblock/

We need to update it to include the source code link. Thanks 👍🏽

**Pull request merged**
